-- MySQL Script generated by MySQL Workbench
-- 05/15/17 20:38:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bamazon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bamazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bamazon` DEFAULT CHARACTER SET utf8 ;
USE `bamazon` ;

-- -----------------------------------------------------
-- Table `bamazon`.`tblcustadd02`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bamazon`.`tblcustadd02` (
  `PK_ADDID02` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_CUSTID02` INT(30) NOT NULL,
  `CUSTADD102` VARCHAR(45) NULL DEFAULT NULL,
  `CUSTADD202` VARCHAR(30) NULL DEFAULT NULL,
  `CUSTCITY02` VARCHAR(45) NULL DEFAULT NULL,
  `CUSTSTATE02` VARCHAR(15) NULL DEFAULT NULL,
  `CUSTZIP02` VARCHAR(10) NULL DEFAULT NULL,
  `CUSTISCURRENT02` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`PK_ADDID02`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bamazon`.`tblcustcard03`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bamazon`.`tblcustcard03` (
  `PK_CARDID03` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_ADDID03` INT(30) NOT NULL,
  `CARDNUM03` VARCHAR(30) NOT NULL,
  `CARDNAME03` VARCHAR(30) NOT NULL,
  `CVVNUM03` CHAR(5) NULL DEFAULT NULL,
  `BANKNAME03` VARCHAR(30) NOT NULL,
  `EXPDATE03` CHAR(4) NOT NULL,
  `ISCURRENT03` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_CARDID03`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bamazon`.`tblcusthead01`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bamazon`.`tblcusthead01` (
  `PK_CUSTID01` INT(11) NOT NULL AUTO_INCREMENT,
  `TYPEID01` VARCHAR(5) NOT NULL DEFAULT 'MEM',
  `MEMSINCE01` VARCHAR(8) NULL DEFAULT NULL,
  `CUSTEMAIL01` VARCHAR(45) NULL DEFAULT NULL,
  `CONTACTNUM01` VARCHAR(30) NULL DEFAULT NULL,
  `CUSTUSERNAME01` VARCHAR(30) NULL DEFAULT NULL,
  `CUSTUSERPWD` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_CUSTID01`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bamazon`.`tblorddet05`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bamazon`.`tblorddet05` (
  `PK_ORDDETID05` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_ORDID05` INT(30) NOT NULL,
  `FK_ITEMID05` INT(30) NOT NULL,
  `ORDQTY05` INT(30) NOT NULL,
  `ORDDISC05` VARCHAR(30) NULL DEFAULT NULL,
  `ORDMTKCODE05` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ORDDETID05`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bamazon`.`tblordhead04`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bamazon`.`tblordhead04` (
  `PK_ORDID04` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_CUSTID04` VARCHAR(30) NULL DEFAULT NULL,
  `FK_ADDID04` INT(30) NULL DEFAULT NULL,
  `ORDTAX04` FLOAT(10,2) NULL DEFAULT NULL,
  `ORDSHIPP04` VARCHAR(4) NULL DEFAULT NULL,
  `ORDTOTAL04` FLOAT(10,2) NULL DEFAULT NULL,
  `ORDSTATUS04` VARCHAR(5) NULL DEFAULT NULL,
  `ORDPAID04` CHAR(1) NULL DEFAULT NULL,
  `ORDPAYMODE04` VARCHAR(4) NULL DEFAULT NULL,
  `FK_CARDID04` VARCHAR(30) NULL DEFAULT NULL,
  `ORDSPLREM04` VARCHAR(45) NULL DEFAULT NULL,
  `ORDTRACK04` VARCHAR(50) NULL DEFAULT NULL,
  `ORDERDATE` VARCHAR(8) NULL DEFAULT NULL,
  `ORDITEMID04` VARCHAR(30) NULL DEFAULT NULL,
  `ORDQTY04` INT(10) NULL DEFAULT NULL,
  `ORDTOT4` FLOAT(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ORDID04`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bamazon`.`tblstockhead06`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bamazon`.`tblstockhead06` (
  `PK_ITEMID06` INT(11) NOT NULL AUTO_INCREMENT,
  `ITEMNAME06` VARCHAR(50) NOT NULL,
  `ITEMDESC06` VARCHAR(60) NULL DEFAULT NULL,
  `ITEMSTOCK06` FLOAT(30,2) NULL DEFAULT NULL,
  `ITEMREORDER06` FLOAT(30,2) NULL DEFAULT NULL,
  `ITEMBIN06` VARCHAR(10) NULL DEFAULT NULL,
  `ITEMAISLE06` VARCHAR(5) NULL DEFAULT NULL,
  `ITEMLASTSUP06` VARCHAR(30) NULL DEFAULT NULL,
  `ITEMRATE06` FLOAT(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ITEMID06`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

USE `bamazon` ;

-- -----------------------------------------------------
-- procedure SPDISPLAYSTOCK
-- -----------------------------------------------------

DELIMITER $$
USE `bamazon`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPDISPLAYSTOCK`()
BEGIN
SELECT PK_ITEMID06,ITEMNAME06,ITEMDESC06,ITEMSTOCK06 FROM TBLSTOCKHEAD06;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SPINSERTMEMBER
-- -----------------------------------------------------

DELIMITER $$
USE `bamazon`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPINSERTMEMBER`(IN MEMSINCE01V VARCHAR(5),IN CUSTEMAIL01V VARCHAR(30),IN CONTACTNUM01V VARCHAR(30),IN CUSTUSERNAME01V VARCHAR(40),IN CUSTUSERPWDV VARCHAR(30))
BEGIN
INSERT INTO bamazon.tblcusthead01 (`MEMSINCE01`, `CUSTEMAIL01`, `CONTACTNUM01`, `CUSTUSERNAME01`, `CUSTUSERPWD`)
VALUES (`MEMSINCE01V`, `CUSTEMAIL01V`, `CONTACTNUM01V`, `CUSTUSERNAME01V`, `CUSTUSERPWDV` );

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SPPOPULARITEMS
-- -----------------------------------------------------

DELIMITER $$
USE `bamazon`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPPOPULARITEMS`()
BEGIN
SELECT ORDITEMID04,COUNT(*) AS SALECOUNT,ITEMNAME06,ITEMDESC06 FROM TBLSTOCKHEAD06 AS A 
INNER JOIN 
TBLORDHEAD04 AS B ON A.PK_ITEMID06 = B.ORDITEMID04 AND ITEMSTOCK06>0 
GROUP BY B.ORDITEMID04 
ORDER BY COUNT(*) DESC  
LIMIT 10;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SPUSERAUTH
-- -----------------------------------------------------

DELIMITER $$
USE `bamazon`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPUSERAUTH`(IN UNAME1 VARCHAR(255),IN PWD1 VARCHAR(255),OUT FOUNDUSER VARCHAR(30))
BEGIN
DECLARE TOTROW1 INTEGER(10);
SET @UNAME=UNAME1;
SET @PWD = PWD1;

SELECT 
    COUNT(*)
INTO @TOTROW FROM
    TBLCUSTHEAD01
WHERE
    CUSTUSERNAME01 = @UNAME
	AND CUSTUSERPWD = @PWD;

SELECT @TOTROW;

SET TOTROW1=@TOTROW;
	IF @TOTROW>0 THEN 
    SET FOUNDUSER = "TRUE";
    
   	ELSE 
		SET FOUNDUSER = "FALSE";
	END IF ;
SELECT FOUNDUSER;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showOrdHist
-- -----------------------------------------------------

DELIMITER $$
USE `bamazon`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `showOrdHist`(IN UNAME1 varchar(30))
BEGIN
SET @UNAME=UNAME1;
SELECT PK_ORDID04,
FK_CUSTID04,
ITEMNAME06,
ORDQTY04,
ORDQTY04*ITEMRATE06 AS AMT
FROM bamazon.tblordhead04 as A 
INNER JOIN tblstockhead06 
on ORDITEMID04=PK_ITEMID06 and A.FK_CUSTID04=@UNAME ;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
